### ISSUE TITLE
Routing to functions fails when `accept` header has more than one option

### ISSUE THREAD

**Issue by rlgod** [gertjvr/serverless-plugin-simulate#38]
# This is a Bug Report

## Description

For bug reports:
* http requests can have `accept` headers with multiple values like `application/json, text/html, */*` but this will cause the request to fail.
* The request should be fulfilled when multiple options are passed
* A function with `integration: lambda`

## Additional Data
* ***Serverless Framework Version you're using***:
1.6.1
* ***Serverless Docker Plugin Version you're using***:
* ***Operating System***:
OSX Sierra 10.12.3
* ***Stack Trace***:
```
Error: No veolicty template is set
    at Object.event (/Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/lib/integration/lambda.js:12:24)
    at Object.event (/Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/lib/integration/index.js:17:40)
    at /Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/lib/integration/middleware.js:18:15
    at Layer.handle [as handle_request] (/Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/node_modules/express/lib/router/route.js:137:13)
    at cors (/Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/node_modules/cors/lib/index.js:179:7)
    at /Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/node_modules/cors/lib/index.js:229:17
    at originCallback (/Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/node_modules/cors/lib/index.js:218:15)
    at /Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/node_modules/cors/lib/index.js:223:13
    at optionsCallback (/Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/node_modules/cors/lib/index.js:204:9)
    at corsMiddleware (/Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/node_modules/cors/lib/index.js:209:7)
    at Layer.handle [as handle_request] (/Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/node_modules/express/lib/router/layer.js:95:5)
    at /Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/node_modules/express/lib/router/index.js:275:10)
    at /Users/daniel/Documents/Programming/school/service-forum/node_modules/serverless-plugin-simulate/lib/authorizer/middleware.js:44:7
    at tryCatcher (/Users/daniel/Documents/Programming/school/service-forum/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/daniel/Documents/Programming/school/service-forum/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/daniel/Documents/Programming/school/service-forum/node_modules/bluebird/js/release/promise.js:567:18)
```
* ***Provider Error messages***:

**Comment by rlgod** [comment]
I have a fix ready for this which I'll PR soon
